name: CI

on:
  push:
  pull_request:

jobs:
  tree-sitter-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Rust toolchain ----------
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      # ---------- tree-sitter ----------
      - name: Install tree-sitter-cli
        run: cargo install tree-sitter-cli --locked

      - name: Generate C parser
        run: tree-sitter generate

      - name: Run corpus tests
        run: tree-sitter test